((org-mode . ((fill-column . 1500)
	      (org-description-max-indent . 5)
	      (org-src-preserve-indentation . 't)
	      (truncate-lines . nil)
	      (mode . iimage)
	      (mode . visual-line)
	      ))
 )
